### PR TITLE
define `convert` for Samples

### LINKED ISSUE #156: Deserializing Arrow tables with nested `Samples` fails on newer Arrow's
```julia
ERROR: MethodError: Cannot `convert` an object of type 
  Samples{Base.ReshapedArray{UInt8, 2, SubArray{UInt8, 1, Arrow.Primitive{UInt8, Vector{UInt8}}, Tuple{UnitRange{Int64}}, true}, Tuple{}}} to an object of type 
  Samples{Matrix{UInt8}}

Closest candidates are:
  convert(::Type{T}, ::Intervals.AnchoredInterval{P, T}) where {P, T}
   @ Intervals ~/.julia/packages/Intervals/V53WF/src/anchoredinterval.jl:181
  convert(::Type{T}, ::Intervals.Interval{T}) where T
   @ Intervals ~/.julia/packages/Intervals/V53WF/src/interval.jl:240
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:84
  ...

Stacktrace:
  [1] setindex!(A::Vector{Samples{Matrix{…}}}, x::Samples{Base.ReshapedArray{UInt8, 2, SubArray{…}, Tuple{}}}, i1::Int64)
    @ Base ./array.jl:1021
  [2] copyto_unaliased!(deststyle::IndexLinear, dest::Vector{…}, srcstyle::IndexLinear, src::Arrow.Struct{…})
    @ Base ./abstractarray.jl:1088
  [3] copyto!(dest::Vector{Samples{…}}, src::Arrow.Struct{Samples{…}, Tuple{…}, (:data, :info, :encoded)})
    @ Base ./abstractarray.jl:1068
  [4] copymutable(a::Arrow.Struct{Samples{…}, Tuple{…}, (:data, :info, :encoded)})
    @ Base ./abstractarray.jl:1202
  [5] copy
    @ ./abstractarray.jl:1145 [inlined]
  [6] _preprocess_column(col::Arrow.Struct{Samples{…}, Tuple{…}, (:data, :info, :encoded)}, len::Int64, copycols::Bool)
    @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:243
```
I believe since Arrow started returning these views.

I think it's kinda reasonable to define a convert that forwards to the convert for the inner matrix:
```julia
function Base.convert(::Type{Onda.Samples{Matrix{T}}}, obj::Onda.Samples{<:Base.ReshapedArray{T, 2, <:SubArray{T}}}) where {T <: Number}
    (; data, info, encoded) = obj
    return Samples(convert(Matrix{T}, data), info, encoded)
end
```

Note `Matrix{T}` is indeed the deserialization target: https://github.com/beacon-biosignals/Onda.jl/blob/dbeab57ef71939c134e06a527100a0db383be98d/src/samples.jl#L581

### PR DESCRIPTION
**Pull request by ericphanson**
closes #156 

I chose not to update the encoding parameters when converting encoded samples, since that seemed like a change we don't want to make implicitly.

### CODE REVIEW

File: src/samples.jl [hunk 1]
```diff
@@ -80,6 +80,10 @@ function Base.hash(a::Samples, h::UInt)
     return hash(Samples, hash(a.encoded, hash(a.info, hash(a.data, h))))
 end
 
+function Base.convert(::Type{Samples{T}}, samples::Samples) where {T}
+    return Samples(convert(T, samples.data), samples.info, samples.encoded)
+end
```
Comment (kleinschmidt) [inline src/samples.jl:85]: I don't think we want to convert encoded samples like this...I think you can easily get into trouble if you for instance convert Int8 encoded samples to Float32 adn then save them with `store`, you'll get totally wrong Signal (`store` just calls `write_lpcm` with `encode(samples).data` https://github.com/beacon-biosignals/Onda.jl/blob/97446538cedb2017d575097cc128eeea8755bd52/src/samples.jl#L519 and `encode` does nothing if `samples.encoded` is true).
```suggestion
function Base.convert(::Type{Samples{T}}, samples::Samples) where {T}
    samples.encoded && throw(ArgumentError("can't `convert` encoded samples; use `decode` first"))
    return Samples(convert(T, samples.data), samples.info, samples.encoded)
end
```

Comment (ericphanson) [reply src/samples.jl:85]: I'm fine with fully disallowing this, but I did test that validation will catch this issue:
```julia
    # For encoded samples, in generally we cannot `convert`.
    # We choose to not update encoding parameter in `convert`, since `convert` can be implied
    # implicitly, and changing the encoding parameters seems like too big of a change.
    # Therefore, validation errors.
    samples = Samples(rand(sample_type(info), 3, 100), info, true)
    err = ArgumentError("encoded `data` matrix eltype does not match `sample_type(info)`")
    @test_throws err convert(Samples{Matrix{Int32}}, samples)
```

File: test/samples.jl [hunk 2]
```diff
@@ -212,6 +212,42 @@ Base.read(p::BufferPath) = take!(p.io)
...
+    rt = rt_table[1, "col"]
+    @test rt.data isa AbstractMatrix{Float32}
+    @test rt == samples
+
+    # For encoded samples, in generally we cannot `convert`.
+    # We choose to not update encoding parameter in `convert`, since `convert` can be implied
+    # implicitly, and changing the encoding parameters seems like too big of a change.
+    # Therefore, validation errors.
+    samples = Samples(rand(sample_type(info), 3, 100), info, true)
+    err = ArgumentError("encoded `data` matrix eltype does not match `sample_type(info)`")
```
Comment (ericphanson) [inline test/samples.jl:247]:
```suggestion
    err = ArgumentError("can't `convert` encoded samples; use `decode` first")
```

File: test/samples.jl [hunk 3]
```diff
@@ -212,6 +212,42 @@ Base.read(p::BufferPath) = take!(p.io)
...
+    # Here, materializing this table in this way threw an error before `convert` was defined
+    rt_table = DataFrame(Arrow.Table(Arrow.tobuffer(table)); copycols=true)
+    rt = rt_table[1, "col"]
+    @test rt.data isa AbstractMatrix{Float32}
+    @test rt == samples
+
+    # For encoded samples, in generally we cannot `convert`.
+    # We choose to not update encoding parameter in `convert`, since `convert` can be implied
+    # implicitly, and changing the encoding parameters seems like too big of a change.
+    # Therefore, validation errors.
```
Comment (ericphanson) [inline test/samples.jl:245]:
```suggestion
```

File: src/samples.jl (hunk 1 above)
Comment (kleinschmidt) [reply src/samples.jl]: ahh right, the validation in the constructor, forgot about that.  I guess there's very little usefulness in using convert on encoded since you'd have to already have samples with a _different_ eltype and you're converting to the correct type for it to pass validation...

**Review by kleinschmidt — APPROVED** [review]
